version: '3'

services:
  order_system_postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=oms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      gin_network:
        ipv4_address: 10.6.0.5

networks:
  gin_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
